In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv("titles.csv")

In [4]:
df

title  year
0               The Rising Son  1990
1      The Thousand Plane Raid  1969
2             Crucea de piatra  1993
3                      Country  2000
4                   Gaiking II  2011
...                        ...   ...
49995                    Rebel  1970
49996                  Suzanne  1996
49997                    Bomba  2013
49998     Aao Jao Ghar Tumhara  1984
49999               Mrs. Munck  1995

[50000 rows x 2 columns]

In [5]:
df.head()

title  year
0           The Rising Son  1990
1  The Thousand Plane Raid  1969
2         Crucea de piatra  1993
3                  Country  2000
4               Gaiking II  2011

In [6]:
df.tail()

title  year
49995                 Rebel  1970
49996               Suzanne  1996
49997                 Bomba  2013
49998  Aao Jao Ghar Tumhara  1984
49999            Mrs. Munck  1995

In [7]:
df["title"]

0                 The Rising Son
1        The Thousand Plane Raid
2               Crucea de piatra
3                        Country
4                     Gaiking II
                  ...           
49995                      Rebel
49996                    Suzanne
49997                      Bomba
49998       Aao Jao Ghar Tumhara
49999                 Mrs. Munck
Name: title, Length: 50000, dtype: object

In [8]:
df["year"]

0        1990
1        1969
2        1993
3        2000
4        2011
         ... 
49995    1970
49996    1996
49997    2013
49998    1984
49999    1995
Name: year, Length: 50000, dtype: int64

In [9]:
after85=df[df["year"]>1985]

In [10]:
after85

title  year
0        The Rising Son  1990
2      Crucea de piatra  1993
3               Country  2000
4            Gaiking II  2011
5           Medusa (IV)  2015
...                 ...   ...
49990           Junebug  2005
49993    Corruption.Gov  2010
49996           Suzanne  1996
49997             Bomba  2013
49999        Mrs. Munck  1995

[29814 rows x 2 columns]

In [11]:
cast=pd.read_csv("cast.csv")

In [12]:
cast

title  year                        name     type  \
0                Closet Monster  2015                    Buffy #1    actor   
1               Suuri illusioni  1985                      Homo $    actor   
2           Battle of the Sexes  2017                     $hutter    actor   
3          Secret in Their Eyes  2015                     $hutter    actor   
4                    Steve Jobs  2015                     $hutter    actor   
...                         ...   ...                         ...      ...   
74996  Mia fora kai ena... moro  2011     Penelope Anastasopoulou  actress   
74997         The Magician King  2004       Tiannah Anastassiades  actress   
74998        Festival of Lights  2010             Zoe Anastassiou  actress   
74999                Toxic Tutu  2016             Zoe Anastassiou  actress   
75000           Fugitive Pieces  2007  Anastassia Anastassopoulou  actress   

                     character     n  
0                      Buffy 4  31.0  
1                       Guests  22.0  
2              Bobby Riggs Fan  10.0  
3              2002 Dodger Fan   NaN  
4      1988 Opera House Patron   NaN  
...                        ...   ...  
74996       Popi voulkanizater  11.0  
74997  Unicycle Race Attendant   NaN  
74998       Guidance Counselor  20.0  
74999        Demon of Toxicity   NaN  
75000             Laundry Girl  25.0  

[75001 rows x 6 columns]

In [13]:
t=df
movies90=t[(t['year']>=1990) & (t['year']>=2000)]


In [14]:
movies90

title  year
3                             Country  2000
4                          Gaiking II  2011
5                         Medusa (IV)  2015
6      The Fresh Air Will Do You Good  2008
8                          L'outsider  2016
...                               ...   ...
49984          No quiero ser recuerdo  2014
49989                         Vincere  2009
49990                         Junebug  2005
49993                  Corruption.Gov  2010
49997                           Bomba  2013

[23114 rows x 2 columns]

In [15]:
c=cast
c["n"].isnull().head()

0    False
1    False
2    False
3     True
4     True
Name: n, dtype: bool

In [16]:
c=cast
c_fill=c[c["n"].isnull()].fillna("NA")

In [17]:
c_fill

title  year                        name     type  \
3        Secret in Their Eyes  2015                     $hutter    actor   
4                  Steve Jobs  2015                     $hutter    actor   
5      Straight Outta Compton  2015                     $hutter    actor   
6      Straight Outta Compton  2015                     $hutter    actor   
7              For Thy Love 2  2009                Bee Moe $lim    actor   
...                       ...   ...                         ...      ...   
74984                    Ovum  2015  Christina Rosas Anastasiou  actress   
74985                  7 avlu  2009         Evmorfia Anastasiou  actress   
74993     I teliki apopliromi  2013         Mara Anastasopoulou  actress   
74997       The Magician King  2004       Tiannah Anastassiades  actress   
74999              Toxic Tutu  2016             Zoe Anastassiou  actress   

                           character   n  
3                    2002 Dodger Fan  NA  
4            1988 Opera House Patron  NA  
5                        Club Patron  NA  
6                            Dopeman  NA  
7                             Thug 1  NA  
...                              ...  ..  
74984  Fertility Clinic Receptionist  NA  
74985                          Eleni  NA  
74993                Marina's friend  NA  
74997        Unicycle Race Attendant  NA  
74999              Demon of Toxicity  NA  

[28966 rows x 6 columns]

In [18]:
t=df
t[t["title"]=="MAA"]

Empty DataFrame
Columns: [title, year]
Index: []

In [19]:
df1=pd.read_csv("data.csv")

In [20]:
df1

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [21]:
newdf=df1.dropna()

In [22]:
newdf

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[164 rows x 4 columns]

In [23]:
newdf=df1.dropna(subset=["Duration","Pulse"])

In [24]:
newdf

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [25]:
newdf=df.dropna(axis=0)

In [26]:
newdf

title  year
0               The Rising Son  1990
1      The Thousand Plane Raid  1969
2             Crucea de piatra  1993
3                      Country  2000
4                   Gaiking II  2011
...                        ...   ...
49995                    Rebel  1970
49996                  Suzanne  1996
49997                    Bomba  2013
49998     Aao Jao Ghar Tumhara  1984
49999               Mrs. Munck  1995

[50000 rows x 2 columns]

In [27]:
newdf=df1.dropna()

In [28]:
newdf

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[164 rows x 4 columns]

In [29]:
import pandas as pd
 
# creating a sample dataframe
data = pd.DataFrame({'Brand': ['Maruti', 'Hyundai', 'Tata',
                            'Mahindra', 'Maruti', 'Hyundai',
                            'Renault', 'Tata', 'Maruti'],
                    'Year': [2012, 2014, 2011, 2015, 2012,
                            2016, 2014, 2018, 2019],
                    'Kms Driven': [50000, 30000, 60000,
                                    25000, 10000, 46000,
                                    31000, 15000, 12000],
                    'City': ['Gurgaon', 'Delhi', 'Mumbai',
                            'Delhi', 'Mumbai', 'Delhi',
                            'Mumbai', 'Chennai', 'Ghaziabad'],
                    'Mileage': [28, 27, 25, 26, 28,
                                29, 24, 21, 24]})

In [30]:
data

Brand  Year  Kms Driven       City  Mileage
0    Maruti  2012       50000    Gurgaon       28
1   Hyundai  2014       30000      Delhi       27
2      Tata  2011       60000     Mumbai       25
3  Mahindra  2015       25000      Delhi       26
4    Maruti  2012       10000     Mumbai       28
5   Hyundai  2016       46000      Delhi       29
6   Renault  2014       31000     Mumbai       24
7      Tata  2018       15000    Chennai       21
8    Maruti  2019       12000  Ghaziabad       24

In [31]:
g=data.loc[(data.Brand=="Maruti")&(data.Mileage>25)]

In [32]:
g

Brand  Year  Kms Driven     City  Mileage
0  Maruti  2012       50000  Gurgaon       28
4  Maruti  2012       10000   Mumbai       28

In [33]:
g=data.loc[2:5]

In [34]:
g

Brand  Year  Kms Driven    City  Mileage
2      Tata  2011       60000  Mumbai       25
3  Mahindra  2015       25000   Delhi       26
4    Maruti  2012       10000  Mumbai       28
5   Hyundai  2016       46000   Delhi       29

In [35]:
f=data.iloc[[0, 2, 4, 7]]

In [36]:
f

Brand  Year  Kms Driven     City  Mileage
0  Maruti  2012       50000  Gurgaon       28
2    Tata  2011       60000   Mumbai       25
4  Maruti  2012       10000   Mumbai       28
7    Tata  2018       15000  Chennai       21

In [37]:
import numpy as np
 
a_1d = np.arange(3)
print(a_1d)

[0 1 2]


In [38]:
a_2d = np.arange(12).reshape((3, 4))
print(a_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [39]:
a_3d = np.arange(24).reshape((2, 3, 4))
print(a_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [40]:
arr_1D = np.array( [2,4,6,8] )     # create  NumPy 1D array which contain int value 2,4,6,8
print(arr_1D)         # print arr_1D

[2 4 6 8]


In [41]:
arr_2D = np.array ([ [0, 1, 1], [1, 0, 1], [1, 1, 0] ] )         # Create Numpy 2D array which contain inter type valye
print(arr_2D) # print arr_1D

[[0 1 1]
 [1 0 1]
 [1 1 0]]


In [42]:
c = np.array([(1,2,3),
              (4,5,6)])
print(c.shape)
(2, 3)

(2, 3)


(2, 3)

In [43]:
import numpy as np 
a = np.array([1, 2, 3], dtype = complex) 
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [44]:
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float') 
print ("Array created using passed list:\n", a) 

Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]


In [45]:
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float') 
np.conj(a)
print ("Array created using passed list:\n", a) 

Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]


In [46]:
import numpy as np
 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
 
newarr = arr.reshape(2, 3, 2)
 
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
flarr = arr.flatten()
 
print ("\nOriginal array:\n", arr) 


Original array:
 [[1 2 3]
 [4 5 6]]


In [48]:
print ("Fattened array:\n", flarr)

Fattened array:
 [1 2 3 4 5 6]


In [54]:
np.random.rand(4)

array([0.18620302, 0.15049296, 0.38255545, 0.5119503 ])

In [50]:
np.random.rand(4,3)

array([[0.48902687, 0.83548427, 0.17952902],
       [0.73493163, 0.39802236, 0.10411257],
       [0.03103023, 0.84875695, 0.0239338 ],
       [0.80222336, 0.98059875, 0.6050532 ]])

In [51]:
np.random.rand(4,3,2)

array([[[0.45831207, 0.43424279],
        [0.42525269, 0.63505455],
        [0.91738824, 0.35928804]],

       [[0.88440308, 0.18721595],
        [0.042714  , 0.83861576],
        [0.21756994, 0.6100654 ]],

       [[0.11598124, 0.94961975],
        [0.88511371, 0.22999049],
        [0.71558313, 0.3466679 ]],

       [[0.75535357, 0.07320478],
        [0.43195602, 0.08349015],
        [0.82254744, 0.80931489]]])

In [52]:
np.random.randn()

-1.4767114366946843

In [ ]:
pip